version: '3'

services:
    nginix:
        build: nginx
        links:
            - fullstack
        ports:
            - "8080:80"
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=testpass
            - MYSQL_DATABASE=challenge
        volumes:
            - devmysqldb:/var/lib/mysql
            - ./db/sql:/docker-entrypoint-initdb.d

    backend:
        build: backend-node
        links:
            - db
            - redis
        ports:
            - "18000:8000"

    fullstack:
        build: frontend-react
        links:
            - backend
        ports:
            - "13000:3000"
    redis:
        image: redis
        ports:
            - "6379:6379"

volumes:  
    devmysqldb:
