version: '3'

services:
    nginx:
        image: nginx:latest
        links:
            - fullstack
        ports:
            - 8000:80
        volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=testpass
            - MYSQL_DATABASE=challenge
        volumes:
            - devmysqldb:/var/lib/mysql
            - ./db/sql:/docker-entrypoint-initdb.d

    backend:
        build: backend-node
        links:
            - db
        ports:
            - "18000:8000"

    fullstack:
        build: frontend-react
        links:
            - backend
        ports:
            - "13000:3000"
    redis:
        image: redis
        ports:
            - "6379"

volumes:  
    devmysqldb:
